/*
Script generated by Aqua Data Studio 16.0.3 on May-07-2015 12:36:24 AM
Database: pbi_manager
Schema: <DEFAULT>
Objects: TABLE, VIEW, PROCEDURE, FUNCTION, TRIGGER, EVENT
*/
DROP TABLE "PBI_USER"
GO
DROP TABLE "PBI_UPDATES"
GO
DROP TABLE "PBI_LIST"
GO

CREATE TABLE "PBI_LIST"  ( 
	"PBI_ID"              	decimal(10,0) NOT NULL,
	"PBI_DESCR"           	varchar(255) NULL,
	"PBI_DOCUMENTATION"   	decimal(10,0) NOT NULL,
	"PBI_MERGED"          	decimal(10,0) NOT NULL,
	"PBI_VALIDATED_BY_PO" 	decimal(10,0) NOT NULL,
	"PBI_DEPLOYABLE"      	decimal(10,0) NOT NULL,
	"PBI_DEPLOYED_TO_DEMO"	decimal(10,0) NOT NULL,
	PRIMARY KEY("PBI_ID")
)
GO
CREATE TABLE "PBI_UPDATES"  ( 
	"PBI_ID"         	decimal(10,0) NOT NULL,
	"PBI_USER_ID"    	decimal(10,0) NOT NULL,
	"PBI_UPDATE_DATE"	date NOT NULL 
	)
GO
CREATE TABLE "PBI_USER"  ( 
	"USER_ID"    	int(11) NOT NULL,
	"USER_NAME"  	varchar(100) NOT NULL,
	"USER_ACTIVE"	int(11) NOT NULL,
	PRIMARY KEY("USER_ID")
)
GO

